on: 
  push:
  workflow_dispatch:
  

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: diff
        uses: GrantErickson/hello-world-javascript-action@main
        with:
          who-to-greet: 'The Six-Fingered Man'
          token: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.diff.outputs.time }}"
      # Show the diff of PR #1
      - name: PR #1 diff
        run: echo "Diff is ${{ steps.diff.outputs.diff }}"
